name: VR Development
favicon: null
layout_spectrum: 0.014266664162278175
typography_spectrum: 0.3835865755099803
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.20066562830470502
purpose:
  - name: shares
    item: null
    url: null
